# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='fb_id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='insta_id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='vk_id',
            field=models.URLField(blank=True, null=True),
        ),
    ]
