# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100)),
                ('hall_address', models.CharField(blank=True, max_length=100)),
                ('hall_max_places', models.IntegerField(blank=True, default=10, null=True)),
            ],
            options={
                'db_table': 'hall',
            },
        ),
    ]
