# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100)),
                ('hall_address', models.CharField(blank=True, max_length=100)),
                ('hall_max_places', models.IntegerField(blank=True, default=10, null=True)),
                ('hall_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('hall_price_in_hour', models.IntegerField(blank=True, null=True)),
                ('hall_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hall',
            },
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shows_names', models.CharField(max_length=100)),
                ('shows_time_length', models.TimeField(blank=True, default='01:00')),
                ('shows_description', models.CharField(blank=True, max_length=400, null=True)),
                ('shows_image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'db_table': 'shows',
            },
        ),
    ]
