# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients_base', '0002_auto_20170516_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_price', models.IntegerField(default=1)),
                ('place_status', models.CharField(default='FREE', max_length=4)),
                ('date_add', models.DateTimeField(default=datetime.datetime(2017, 5, 23, 9, 42, 53, 855086, tzinfo=utc))),
                ('date_change', models.DateTimeField()),
                ('comment', models.TextField(max_length=500)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients_base.Clients')),
            ],
            options={
                'db_table': 'eventplace',
            },
        ),
        migrations.CreateModel(
            name='EventsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_place_count', models.IntegerField(default=15)),
                ('event_place_current_count', models.IntegerField(default=0)),
                ('event_vk_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100)),
                ('hall_address', models.CharField(blank=True, max_length=100)),
                ('hall_max_places', models.IntegerField(blank=True, default=10, null=True)),
                ('hall_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('hall_price_in_hour', models.IntegerField(blank=True, null=True)),
                ('hall_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hall',
            },
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shows_names', models.CharField(max_length=100)),
                ('shows_time_length', models.TimeField(blank=True, default='01:00')),
                ('shows_description', models.CharField(blank=True, max_length=400, null=True)),
                ('shows_image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'db_table': 'shows',
            },
        ),
        migrations.AddField(
            model_name='eventsinfo',
            name='events_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_base.Hall'),
        ),
        migrations.AddField(
            model_name='eventsinfo',
            name='events_show_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_base.Shows'),
        ),
        migrations.AddField(
            model_name='eventplace',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_base.EventsInfo'),
        ),
    ]
