# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsinfo',
            name='event_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventplace',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 10, 2, 10, 123920, tzinfo=utc)),
        ),
    ]
