# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 06:17
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events_base', '0002_hall_hall_price_in_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='hall_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
