# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_base', '0003_hall_hall_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='hall_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
