# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events_base', '0003_auto_20170525_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplace',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 30, 8, 58, 7, 343115, tzinfo=utc)),
        ),
    ]
